### ISSUE TITLE
Should we move this lab from `A Deeper Dive into OO` into `Object Relations`

### ISSUE THREAD

**Issue by deniznida** [learn-co-curriculum/oo-data-normalization#13]
right now this lab is the `A Deeper Dive into OO` unit but it uses two classes which are interacting with each other. I think it would make more sense to move into the `Object Relations` unit. Many students had problems understanding this lab without the lecture guiding them.

@AnnJohn

**Comment by AnnJohn** [comment]
@SophieDeBenedetto ^^

**Comment by SophieDeBenedetto** [comment]
@deniznida @AnnJohn this lab has been moved into the object relations unit in the web development with ruby on rails track. closing.
